name: model
environment:
  sdk: '>=2.19.2 <3.0.0'
version: 1.0.0+1
publish_to: 'none'
dependencies:
  freezed_annotation: ^2.2.0
  json_serializable: ^6.7.1
  flutter:
    sdk: flutter
dev_dependencies:
  freezed: ^2.3.2
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
