name: events
environment:
  sdk: '>=2.19.2 <3.0.0'
version: 1.0.0+1
publish_to: 'none'
dependencies:
  model:
    path: ../model
  get_it: ^7.2.0
  injectable: ^2.1.0
  freezed_annotation: ^2.2.0

  flutter:
    sdk: flutter
  json_serializable: ^6.7.1
dev_dependencies:
  freezed: ^2.3.2
  injectable_generator: ^2.1.4
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
